# Generated by Django 4.0.3 on 2022-12-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0003_doclistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
