# Generated by Django 4.0.3 on 2022-12-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0005_remove_doclistitem_content_remove_doclistitem_dateof_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocListItem',
        ),
    ]
