# Generated by Django 4.0.3 on 2022-12-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0006_delete_doclistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
